plugins {
    id 'java'
}

group 'com.daroogie'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.runelite.net'
    }
}

def runeliteVersion = 'latest.release'

dependencies {
    compileOnly "net.runelite:client:${runeliteVersion}"
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation 'junit:junit:4.12'
    testImplementation "net.runelite:client:${runeliteVersion}"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}